###############################################
# Common Keys for all apps
###############################################

x-common-keys: &common-keys
    restart: always
    logging:
      driver: json-file
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
    dns:
      - 1.1.1.1
      - 1.0.0.1
    devices:
      - /dev/dri:/dev/dri

services:
###############################################
# RADARR - Movies
###############################################
  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:rw
      - /volume1/docker/arr-stack/radarr:/config
      - /volume1/data:/data

###############################################
# SONARR - TV Shows
###############################################

  sonarr:
    <<: *common-keys
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/sonarr:/config
      - /volume1/data:/data

###############################################
# LIDARR - Music
###############################################

  lidarr:
    <<: *common-keys
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/lidarr:/config
      - /volume1/data:/data

###############################################
# BAZARR - Subtitles
###############################################

  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/bazarr:/config
      - /data/Media:/data/Media

###############################################
# PROWLARR - Indexer Manager
###############################################

  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/prowlarr:/config

###############################################
# QBITTORRENT - Downloader
###############################################

  qbittorrent:
    <<: *common-keys
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    network_mode: "host"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/qbittorrent:/config
      - /volume1/docker/arr-stack/qbittorrent/data:/data
      - /volume1/data:/data

###############################################
# JELLYFIN - Media Server
###############################################

  jellyfin:
    <<: *common-keys
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    privileged: true
    network_mode: "host"
    group_add: 
      -  105
      -  44
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/jellyfin/config:/config
      - /volume1/data/Media:/data/Media:rW 
      - /volume1/docker/arr-stack/tailscale/lib/tailscale/certs:/certs:rw
    ports:
      - 8096:8096

###############################################
# Plex - Media Server
###############################################

  plex:
    <<: *common-keys
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    network_mode: "host"
    environment:
      - PLEX_CLAIM_TOKEN=claim-RfGygGFppmnfwyBTzyWD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/arr-stack/plex/config:/config:rw
      - /volume1/data/Media:/data/Media:ro
    ports:
      - 32400:32400

###############################################
# Tailscale - Private VPN
###############################################

  tailscale:
    <<: *common-keys
    container_name: tailscale
    image: tailscale/tailscale:latest
    volumes:
      - /volume1/docker/arr-stack/tailscale/tun:/tun
      - /volume1/docker/arr-stack/tailscale/lib:/lib:rw
    environment:
      - TS_AUTH_KEY=tskey-auth-kfiYv5uGXC21CNTRL-ay5oRaMGV2Rd11qrv4kK3RQZHQnhyFm5F
      - TS_STATE_DIR=/tailscale
      - TS_ROUTES=172.17.10.0/24
    network_mode: host
    privileged: true

###############################################
# Seer - Media Request System
###############################################

  seer:
    <<: *common-keys
    container_name: seer
    image: ghcr.io/seerr-team/seerr:latest
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /volume1/docker/arr-stack/seer/app/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    ports:
      - 5055:5055

###############################################
# ARR Stack Dedicated Network
###############################################

networks:
  default:
    name: arr_network

###############################################
###############################################
